### ISSUE TITLE
failed to play the TED video add-ons

### ISSUE THREAD

**Issue by janvda** [janvda/balena-kodi-etcetera#4]
**UPDATE 2019-06-15**  I have renamed the issue as the problem with the "vrt nu" and "youtube" is already fixed (see comments below).

An example of the error found in the log file (`/data/kodi/temp/kodi.log`)

```
2019-06-03 21:58:30.186 T:1692390112  NOTICE: [plugin.video.vrt.nu] VRT NU Addon: settings changed
2019-06-03 21:58:34.198 T:1910148368  NOTICE: Samba is idle. Closing the remaining connections
2019-06-03 21:58:41.889 T:1692390112  NOTICE: [plugin.video.vrt.nu] VRT NU Addon: settings changed
2019-06-03 21:58:48.096 T:1537204960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.StopIteration'>
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/addon.py", line 104, in <module>
                                                router(sys.argv[2][1:])
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/addon.py", line 73, in router
                                                _favorites.get_favorites(ttl=60 * 60)
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 38, in get_favorites
                                                xvrttoken = self._tokenresolver.get_fav_xvrttoken()
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 78, in get_fav_xvrttoken
                                                token = self._get_fav_xvrttoken(token_path)
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 203, in _get_fav_xvrttoken
                                                xvrttoken = TokenResolver._create_token_dictionary(cookiejar)
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 256, in _create_token_dictionary
                                                xvrttoken_cookie = next(cookie for cookie in cookie_jar if cookie.name == 'X-VRT-Token')
                                            StopIteration
                                            -->End of Python script error report<--
2019-06-03 21:58:48.120 T:1766306528   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingcategorytvshows&category=nieuws-en-actua
2019-06-03 21:58:48.129 T:1910148368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingcategorytvshows&category=nieuws-en-actua) failed
```

**Comment by janvda** [comment]
error when trying to play TED talk:
```
2019-06-03 21:59:03.776 T:1766306528  NOTICE: [ADDON] TED Talks v4.2.12 - resources.lib.model.fetcher attempting to open http://feedproxy.google.com/~r/TEDTalks_video/~3/bniOE3b20Qg/phil_plait_the_secret_to_scientific_discoveries_making_mistakes with data
2019-06-03 21:59:03.784 T:1766306528  NOTICE: [ADDON] TED Talks v4.2.12 - loaded cookie : <Cookie _abby=gqhoEj84fr8TmOT for .ted.com/> from /root/.kodi/temp/ted-cookies.lwp
2019-06-03 21:59:03.785 T:1766306528  NOTICE: [ADDON] TED Talks v4.2.12 - loaded cookie : <Cookie _nu=1548892037.441 for www.ted.com/> from /root/.kodi/temp/ted-cookies.lwp
2019-06-03 21:59:04.383 T:1766306528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Could not parse HTML:
                                            <!DOCTYPE html>
                                            <!--[if lt IE 8]> <html class="no-js loggedout oldie ie7" lang="en"> <![endif]-->
                                            <!--[if IE 8]> <html class="no-js loggedout oldie ie8" lang="en"> <![endif]-->
                                            <!--[if gt IE 8]><!--><html class='no-js loggedout' lang='en'><!--<![endif]-->
                                            <head>
                                            <script>
                                              (function (H){
                                              H.className=H.className.replace(/\bno-js\b/,'js');
                                              if (('; '+document.cookie).match(/; _ted_user_id=/)) H.className=H.className.replace(/\bloggedout\b/,'loggedin');
                                              })(document.documentElement)
                                            </script><meta charset='utf-8'>
                                            <meta name="twitter:card" content="summary_large_image" />
                                            <meta name="twitter:site" content="@tedtalks" />
                                            <meta property="twitter:image" content="https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/8eb825ec-70d7-4fa4-aa56-9fcd343e68d0/PhilPlait_2018X-embed.jpg?w=1200" />
                                            <meta name="twitter:app:id:iphone" content="376183339" />
                                            <meta name="twitter:app:id:ipad" content="376183339" />
                                            <meta name="twitter:app:id:googleplay" content="com.ted.android" />
                                            <meta name="twitter:app:name:ipad" content="TED" />
```

**Comment by janvda** [comment]
Another TED error:
```
2019-06-04 17:33:26.789 T:1541915360  NOTICE: [ADDON] Initialized TED Talks v4.2.12 using Python: 2.7.13 (default, Sep 26 2018, 18:42:22) 
                                            [GCC 6.3.0 20170516]'
2019-06-04 17:33:32.500 T:1550308064  NOTICE: Previous line repeats 2 times.
2019-06-04 17:33:32.500 T:1550308064  NOTICE: [ADDON] TED Talks v4.2.12 - resources.lib.model.fetcher attempting to open http://feedproxy.google.com/~r/TEDTalks_video/~3/pisufL0i8VU/amanda_williams_why_i_turned_chicago_s_abandoned_homes_into_art with data
2019-06-04 17:33:32.508 T:1550308064  NOTICE: [ADDON] TED Talks v4.2.12 - loaded cookie : <Cookie _abby=gqhoEj84fr8TmOT for .ted.com/> from /root/.kodi/temp/ted-cookies.lwp
2019-06-04 17:33:32.509 T:1550308064  NOTICE: [ADDON] TED Talks v4.2.12 - loaded cookie : <Cookie _nu=1548892037.441 for www.ted.com/> from /root/.kodi/temp/ted-cookies.lwp
2019-06-04 17:33:33.210 T:1550308064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Could not parse HTML:
                                            <!DOCTYPE html>
                                            <!--[if lt IE 8]> <html class="no-js loggedout oldie ie7" lang="en"> <![endif]-->
                                            <!--[if IE 8]> <html class="no-js loggedout oldie ie8" lang="en"> <![endif]-->
                                            <!--[if gt IE 8]><!--><html class='no-js loggedout' lang='en'><!--<![endif]-->
                                            <head>
...
                                            </script><script>
                                              (function(d,s,u,e,m,r){r=(d.location.search||'').match(/[?&](geo=[A-Z]{2})\b/);e=d.createElement(s),m=d.getElementsByTagName(s)[0];e.async=1;e.src=u+(r?'&'+r[1]:'');m.parentNode.insertBefore(e,m)})(document,'script','https://geo-assets.tedcdn.com/cookie-notice/tcn.js?cb=1.1.4')
                                            </script></body></html>
                                            for url 'http://feedproxy.google.com/~r/TEDTalks_video/~3/pisufL0i8VU/amanda_williams_why_i_turned_chicago_s_abandoned_homes_into_art'
                                            -->End of Python script error report<--
2019-06-04 17:33:33.328 T:1909849360   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ted.talks/?url=http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2FTEDTalks_video%2F%7E3%2FpisufL0i8VU%2Famanda_williams_why_i_turned_chicago_s_abandoned_homes_into_art&mode=playVideo]
```

**Comment by janvda** [comment]
removing and re-installing the "Youtube" addon  (`plugin.video.youtube v6.4.1`) fixed the youtube problem !

I tried the same with "TED" addon (`plugin.video.ted.talks v4.2.12`) but without success.

**Comment by janvda** [comment]
I have the same problem regarding TED and VRT NU addon  when using https://github.com/janvda/balena-kodi that is installed on misty-glitter device.

FYI here the kodi info found at the top of the log file:
```
2019-06-05 08:13:15.930 T:1909562640  NOTICE: -----------------------------------------------------------------------
2019-06-05 08:13:15.930 T:1909562640  NOTICE: Starting Kodi (18.1 Git:20190220-5494e5ffac). Platform: Linux ARM 32-bit
2019-06-05 08:13:15.930 T:1909562640  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2019-06-05 08:13:15.930 T:1909562640  NOTICE: Kodi compiled 2019-02-22 by GCC 6.3.0 for Linux ARM 32-bit version 4.9.82 (264530)
2019-06-05 08:13:15.930 T:1909562640  NOTICE: Running on Raspbian GNU/Linux 9 (stretch), kernel: Linux ARM 32-bit version 4.14.79
2019-06-05 08:13:15.943 T:1909562640  NOTICE: FFmpeg version/source: 4.0.3-Kodi
2019-06-05 08:13:15.943 T:1909562640  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
2019-06-05 08:13:15.943 T:1909562640  NOTICE: ARM Features: Neon enabled
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/arm-linux-gnueabihf/kodi
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/arm-linux-gnueabihf/kodi/addons
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://masterprofile/ is mapped to: /root/.kodi/userdata
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://envhome/ is mapped to: /root
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://home/ is mapped to: /root/.kodi
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://temp/ is mapped to: /root/.kodi/temp
2019-06-05 08:13:15.943 T:1909562640  NOTICE: special://logpath/ is mapped to: /root/.kodi/temp
2019-06-05 08:13:15.943 T:1909562640  NOTICE: The executable running is: /usr/lib/arm-linux-gnueabihf/kodi/kodi-rbpi_v7
2019-06-05 08:13:15.943 T:1909562640  NOTICE: Local hostname: f0bc010
2019-06-05 08:13:15.944 T:1909562640  NOTICE: Log File is located: /root/.kodi/temp/kodi.log
2019-06-05 08:13:15.944 T:1909562640  NOTICE: -----------------------------------------------------------------------
```

Here below the TED error reported.
```
2019-06-05 06:17:02.144 T:1522524896  NOTICE: [ADDON] Initialized TED Talks v4.2.12 using Python: 2.7.13 (default, Sep 26 2018, 18:42:22) 
                                            [GCC 6.3.0 20170516]'
2019-06-05 06:17:09.687 T:1530917600  NOTICE: Previous line repeats 2 times.
2019-06-05 06:17:09.687 T:1530917600  NOTICE: [ADDON] TED Talks v4.2.12 - resources.lib.model.fetcher attempting to open http://feedproxy.google.com/~r/TEDTalks_video/~3/pisufL0i8VU/amanda_williams_why_i_turned_chicago_s_abandoned_homes_into_art with data
2019-06-05 06:17:10.766 T:1530917600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Could not parse HTML:
                                            <!DOCTYPE html>
                                            <!--[if lt IE 8]> <html class="no-js loggedout oldie ie7" lang="en"> <![endif]-->
                                            <!--[if IE 8]> <html class="no-js loggedout oldie ie8" lang="en"> <![endif]-->
                                            <!--[if gt IE 8]><!--><html class='no-js loggedout' lang='en'><!--<![endif]-->
                                            <head>
                                            <script>
   ```

Here below the VRT NU error reported:
```
2019-06-05 07:21:29.669 T:1769370336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.StopIteration'>
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/addon.py", line 104, in <module>
                                                router(sys.argv[2][1:])
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/addon.py", line 94, in router
                                                _favorites.get_favorites(ttl=5 * 60)  # Update favorites more often
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 38, in get_favorites
                                                xvrttoken = self._tokenresolver.get_fav_xvrttoken()
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 78, in get_fav_xvrttoken
                                                token = self._get_fav_xvrttoken(token_path)
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 203, in _get_fav_xvrttoken
                                                xvrttoken = TokenResolver._create_token_dictionary(cookiejar)
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 256, in _create_token_dictionary
                                                xvrttoken_cookie = next(cookie for cookie in cookie_jar if cookie.name == 'X-VRT-Token')
                                            StopIteration
                                            -->End of Python script error report<--
2019-06-05 07:21:29.702 T:1427104480   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingrecent
2019-06-05 07:21:29.704 T:1912013408   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingrecent) failed
```

**Comment by janvda** [comment]
I fixed the issue with the VRT NU addon by logging on in a browser to the VRT NU site and completing the logon forms.  (see also https://github.com/pietje666/plugin.video.vrt.nu/issues/32)

So I am only having an issue with the TED talk addon at this moment.

**Comment by janvda** [comment]
see also https://github.com/janvda/balena-kodi/issues/1

**Comment by janvda** [comment]
I no longer had the issue for a while. Not sure what fixed it (maybe reinstalling/updating the add-on fixed it).
